name: CI

# This file is a copy of github.com/jackc/pgx/.github/workflows/ci.yml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    # Note: The TLS tests are rather finicky. It seems that openssl 3 encrypts certificates differently than older
    # openssl and it does it in a way Go and/or pgx ssl handling code can't handle. So stick with Ubuntu 20.04 until
    # that is figured out.
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    strategy:
      matrix:
        go-version: [1.21]
        pg-version: [12, 13, 14, 15, 16]
        include:
          - pg-version: 12
          - pg-version: 13
          - pg-version: 14
          - pg-version: 15
          - pg-version: 16

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup database server for testing
      run: ci/setup_test.bash
      env:
        PGVERSION: ${{ matrix.pg-version }}

    - name: Test
      run: go test -race ./...
